version: "2"
services:
  arangodb:
    image: arangodb/arangodb:3.1.24
    ports:
      - 8529:8529
    environment:
    # Disable authentication. Useful for testing.
      - ARANGO_NO_AUTH=1
    volumes:
      - ./.:/foxx_services